sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t wilkinsleung/docker-kunbenates-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wilkinsleung/docker-kunbenates-react npm run test -- -- coverage