sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t wilkinsleung/docker-kunbenates-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wilkinsleung/docker-kunbenates-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-kunbenates-react"
  env: "DockerKunbenatesReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-976392945067"
  bucket_path: "docker-kunbenates-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
    